name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  test_and_build:
    name: Test and build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - run: nix flake check
      - name: pnpm install
        run: |
          nix develop --command pnpm install &&
          nix develop --command pnpm generate:dev
      - name: Check Prettier
        run: nix develop --command pnpm format:check
        continue-on-error: true
      - name: Run tests
        run: nix develop --command pnpm test

      - run: nix build .
